# This file generates the GitHub Actions matrix.
include:
  - board: seeeduino_xiao_ble
    shield: forager_left
  - board: seeeduino_xiao_ble
    shield: forager_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
