# This file generates the GitHub Actions matrix.
include:
  - board: seeeduino_xiao_ble
    shield: forager_left
    cmake-args: -DZMK_KEYMAP_FILE="forager_left.keymap"

  - board: seeeduino_xiao_ble
    shield: forager_right
    cmake-args: -DZMK_KEYMAP_FILE="forager_right.keymap"

  - board: seeeduino_xiao_ble
    shield: settings_reset
